### ISSUE TITLE
DimThreads causes spawn a lot of entities

### ISSUE THREAD

**Issue by Thunderrock424242** [SrRapero720/dimthreads#5] opened 2024-01-25 19:58 UTC
when i turn gamerule dimthreaad true it spawns a ton of mobs causing my fps to dop i will send a ss and my log
![Screenshot 2024-01-25 145657](https://github.com/SrRapero720/DimensionalThreading-Reforked/assets/119463825/f4def4c5-0a7b-4831-b982-2266a538114b)
[latest.log](https://github.com/SrRapero720/DimensionalThreading-Reforked/files/14057268/latest.log)

**Comment by Thunderrock424242** [comment] 2024-01-25 19:59
as u can see the map shows the mobs too

**Comment by Thunderrock424242** [comment] 2024-01-25 19:59
they are all bunched together

**Comment by SrRapero720** [comment] 2024-01-31 20:02
for some reason i forgot to answer this

**Comment by Thunderrock424242** [comment] 2024-01-31 23:14
When do you think this will be fixed?

**Comment by Pootleris** [comment] 2024-02-27 18:23
me too fk u
nigur

**Comment by SrRapero720** [comment] 2024-03-10 14:47
ok i forgot to answer this... 2 TIMES
can you test if the new update works properly?
https://www.curseforge.com/minecraft/mc-mods/dimensional-threads

also, can you test if removing Forgery mod solves the issue?

**Comment by Thunderrock424242** [comment] 2024-03-10 23:10
Sure

**Comment by HyperFoxOne** [comment] 2024-03-11 14:04
I also have this problem: at night about 2000+ entity spawn in about a millisecond. Not nice.

**Comment by HyperFoxOne** [comment] 2024-03-11 14:13
> ok i forgot to answer this... 2 TIMES can you test if the new update works properly? https://www.curseforge.com/minecraft/mc-mods/dimensional-threads
> 
> also, can you test if removing Forgery mod solves the issue?

just tried it and it does seem to work properly on the lastest version. Will continue using it and if it breaks again I'll update this

edit:**not fixed at all**

**Comment by SrRapero720** [comment] 2024-04-29 06:36
i need a test setup where i was begin able to reproduce this.
if anyone can please send me a modpack with a minimal modlist

**Comment by HyperFoxOne** [comment] 2024-04-29 06:54
> i need a test setup where i was begin able to reproduce this. if anyone can please send me a modpack with a minimal modlist

My modpack contains 300 mods unfortunately so I don't think I will be able to help. (from what I could see the user who created the issue also has hundreds of mods)

**Comment by Thunderrock424242** [comment] 2024-04-29 13:15
Yea I have 466 mods

**Comment by SrRapero720** [comment] 2024-11-25 00:03
spawncap doesn't seems to be causing the issue
i'll close this for now... until someone can test this issue with _less mods_ (466 are A LOT)

**Closed as not planned by SrRapero720** 2024-11-25 00:03 UTC
Labels: bug, help wanted
