### ISSUE TITLE
🔥 1.19.2 Fatal drop in TPS -2000 point 🔥

### ISSUE THREAD

**Issue by Krimatoria** [SrRapero720/dimthreads#6] opened 2024-02-08 12:39 UTC
Forge 43.3.5, Minecraft 1.19.2
Dimthread-1.19.2-v1.0.0.jar

[08Feb2024 15:15:49.804] [dimthread_overworld/ERROR] [supplementaries/]: [!!!!] Some mods (see below stack trace) have errors which will prevent Supplementaries from working correctly.Continuing anyways but you might experience random crashes. You have been warned

![image](https://github.com/SrRapero720/DimensionalThreading-Reforked/assets/106809386/57565b3b-cd2e-4788-8f24-187a110d659a)
![image](https://github.com/SrRapero720/DimensionalThreading-Reforked/assets/106809386/1910a542-c1b0-4669-bd2f-404b6615b9b7)
![image](https://github.com/SrRapero720/DimensionalThreading-Reforked/assets/106809386/ccdd4669-56b9-48f5-9089-7c2019f5a719)

**Comment by SrRapero720** [comment] 2024-02-09 11:59
spark usage is normal, TPS char isn't.
i will look into it.

**Comment by Krimatoria** [comment] 2024-02-09 16:35
> Использование искры в норме, а TPS - нет. Я буду смотреть в него.

The problem was in the TenebrousLands fashion, they have a dusk_chateau structure.nbt each block consists of one or more Silverfish when destroyed, they spawn until the entire structure breaks. She was causing this TPS failure. Although I still removed the mod for measurements. I can check later if there are any changes.

**Comment by mateus3c** [comment] 2024-02-24 23:29
I actually have the same problem, DTR causes massive lag on my world. [https://spark.lucko.me/e5cCOuXtD7](https://spark.lucko.me/e5cCOuXtD7)

**Comment by SrRapero720** [comment] 2024-03-10 14:38
hello, first of all, to send profilers related to Dimesional Threading please use the next command
`/spark profiler --thread *`

profilers you send me only contains the usage of the main thread, which is unused because all tick is delegated to DimThreads

**Comment by CorneliusCornbread** [comment] 2024-05-18 00:38
> /spark profiler --thread *

https://spark.lucko.me/iS02MAAIjl

Reproduced this on 1.20.1 myself. Interestingly enough it also lags the client as well, dropping frames from 120 FPS to <30. Uninstalling the mod doesn't actually solve the problem either, but not installing the mod on my world with an older version of the world, before dimthread, means no lag.

Incredibly weird.

Oh also, the not lag spikes are when I left the problem area of my world. The lag is located within a very specific spot of a chunk, and cannot be resolved by clearing all blocks from the problem area or trying to kill all entities in the problem area. Leaving thee problem area and unloading the chunks _does_ solve the problem. And yes, it persists between server reboots, regardless of anything I try.

**Comment by SrRapero720** [comment] 2024-05-18 01:34
i noticed few things
1- you're not using the latest version of dimthreads: new version fixes some incompatibility with cupboard, which makes the async entity summoner get oveflowed with a lot of entities because it can't never spawn it on the server thread (because the server thread is not used anymore)
2- neruina is installed, isn't important enough but is just a note for next disscussions

**Comment by CorneliusCornbread** [comment] 2024-05-18 02:00
> i noticed few things 1- you're not using the latest version of dimthreads: new version fixes some incompatibility with cupboard, which makes the async entity summoner get oveflowed with a lot of entities because it can't never spawn it on the server thread (because the server thread is not used anymore) 2- neruina is installed, isn't important enough but is just a note for next disscussions

1. I'm using the latest one posted on Modrinth, so if that's the case Modrinth is out of date.
2. Neruina is the first mod I removed during debugging.

I'll take a look at downloading dimthread off of CF later this week and retesting.

**Closed as completed** 2024-09-19 22:12 UTC
Labels: bug
